#!/bin/bash 
#
# xtuple_autoupdater: 1.0
# Author: danderson@xtuple.com
#
# The script initiates installation of xTuple installer packages (.gz) across multiple systems.
# The list of systems is held in a text file with the format  hostname:port/database  
# This script requires xTuple Updater of at least 2.2.5 with the headless update built in
# and the xTuple systems must have the metric headlessUpdate set to true (t)

# Example:xtuple_autoupdater database_file 
#         

 
usage()
{
    local ProgName=$1;
    echo "Usage: $ProgName -l Location_of_Files -v  DatabaseList"
    echo "       -l Define the directory location of the updater packages if not the current directory"
    echo "       -v Verbose output (not implemented as yet)"
    echo "       DatabaseList: hostname1:port/database1,hostname2:port/database2..." 
    echo "                    or the name of the file which contains hostname and database in separate lines (in the same location as the package files)"
    echo
    echo "       PLEASE NOTE: The target xTuple systems must have the headlessUpdate metric installed and set to TRUE"
    echo "       	      This script also assumes the admin user has the same password in all target databases"
    echo
}

runupdater()
{
    local DBURL=$1;
    local USERNAME=$2;
    local PASSWORD=$3;
    local PACKAGEFILE=$4;
    echo -e "Updating System: ${DBURL} with package ${PACKAGEFILE}
==================================================================" >> xtuple_update.log
 
    ${UPDATERLOCATION}/updater -databaseURL=${DBURL} -username=${USERNAME} -passwd=${PASSWORD} -autorun -file=${PACKAGEFILE} >> xtuple_update.log ;
}

#=====================================Main Script========================================
#
# Set default values for variables 
VERBOSE=0
DATABASELIST=
ADMINUSER="admin"
UPDATERLOCATION=/opt/updater-headless
LOCATION=`pwd`

# Parse the command line arguments with '-'
while getopts l:v o ; do
    case "$o" in
        [?])  usage $0 
              exit 1;;
        v)  VERBOSE=1;;
        l)  LOCATION=$OPTARG;;
    esac
done

shift $(($OPTIND-1))
DATABASELIST=${LOCATION}/$1

# Initialise Log file
cat > xtuple_update.log << EOF
xTuple Multi-System Updater Script
===========================================
Applying xTuple Packages:

EOF

   
# Read in the password from the STDIN
read -s -p "Please enter the Admin database password:" PASSWORD
echo 
echo "Loading xTuple packages from ${LOCATION}"

if [ ${LOCATION: -1} -eq "/" ]; then 
  PACKAGELIST=`ls -L ${LOCATION}*.gz`
else  
  PACKAGELIST=`ls -L ${LOCATION}/*.gz`
fi

echo "Packages Found " ${PACKAGELIST}  
echo ${PACKAGELIST} >> xtuple_update.log

# Start running
if [ -e $DATABASELIST ]; then # read Database Connections from a file
   grep -v '^#' < $DATABASELIST | 
   { while read line; do
     DATABASE=$line    
     DBURL=PSQL7://${DATABASE}
     for PACKAGE in $PACKAGELIST; do
       runupdater "$DBURL" "$ADMINUSER" "$PASSWORD" "${PACKAGE}" ;
     done    
   done; }  

else # DATABASELIST is a comma separated list of hostname:port/database strings.
    # Change the internal separation field. 
    IFS=,
    for DATABASE in $DATABASELIST; do
	    DBURL=PSQL7://${DATABASE}
	    for PACKAGE in $PACKAGELIST; do
          runupdater "$DBURL" "$ADMINUSER" "$PASSWORD" "${PACKAGE}" ;
      done
    done
fi

# Finally move uploaded packages into DONE folder so they cannot be re-uploaded
if [ ! -d "${LOCATION}/done" ]; then
   mkdir ${LOCATION}/done
fi

mv ${LOCATION}/*.gz ${LOCATION}/done

#EOF
